# Generated by Django 5.0.6 on 2024-09-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id_enseignant', models.IntegerField(primary_key=True, serialize=False)),
                ('garde', models.CharField(blank=True, max_length=10, null=True)),
                ('annee_recrutement', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enseignant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id_enseignement', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'enseignement',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
